Repository skulpt/skulpt, pull requests merged in 2021-08, with the labels that each got.

#1346 fix bug #1345
  src/compile.js
  test/unit3/test_skulpt_bugs.py
Labels: bug

#1232 Use terser rather than babel-minify
  package-lock.json
  package.json
  support/build/wrapmodules.js
Labels: build tools

#1347 throw python syntax errors not javascript ones
  src/ast.js
  src/compile.js
Labels: small change

#1349 Ellipsis
  src/builtindict.js
  src/compile.js
  src/generic_alias.js
  src/lib/types.py
  src/nonetype.js
Labels: small change

#1257 add strptime support to datetime module with tests
  src/lib/_strptime.js
  src/lib/datetime.js
  src/lib/time.js
  src/main.js
  src/structseq.js
  support/polyfills/es6.js
  support/time-helpers/README
  support/time-helpers/strftime-min.js
  support/time-helpers/strptime.js
  support/time-helpers/strptime.min.js
  test/unit3/test_datetime.py
  test/unit3/test_strptime.py
Labels: stdlib

#1293 update closure
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies
