Repository skulpt/skulpt, pull requests merged in 2021-09, with the labels that each got.

#1357 fix float formatting when the width is is specified for negative values
  src/formatting.js
  test/unit3/test_float.py
Labels: bug, small change

#1355 fix undeclared variable in datetime
  src/lib/datetime.js
Labels: small change

#1356 fix __contains__ can't suspend
  src/compile.js
  test/unit3/test_suspensions.py
Labels: bug, small change

#1358 time.time() should be increasing
  src/lib/time.js
Labels: bug, small change, stdlib

#1361 Tests/test grammar
  src/builtindict.js
  src/compile.js
  src/lib/test/ann_module3.py
  test/unit3/test_grammar.py
Labels: test coverage

#1367 feat: add lcm function to math module
  src/lib/math.js
  test/unit3/test_math.py
Labels: stdlib

#1372 Add comb function to math module
  src/lib/math.js
  test/unit3/test_math.py
Labels: stdlib

#1371 Add perm function to math module
  src/lib/math.js
  test/unit3/test_math.py
Labels: stdlib

#1369 Add prod function to math module
  src/lib/math.js
  test/unit3/test_math.py
Labels: stdlib

#1373 Add isqrt function to math module
  src/lib/math.js
  test/unit3/test_math.py
Labels: stdlib
